service: my-tdd-service

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10

environment:
    STAGE: ${opt:stage}

plugins:
  - serverless-mocha-plugin
  - serverless-stack-output
  - serverless-offline

functions:
  currentDate:
    handler: date/handler.endpoint
    events:
      - http:
          path: ping/date
          method: get
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping/time
          method: get
custom:
  output:
    file: build/stack.json
